version: 0.0 
os: linux 
files: 
  - source: site 
    destination: /var/www/choixresto/site/
hooks:
  # ApplicationStop:
    # - location: .aws/stopApplication.sh
    # - location: .aws/stopApplicationAuthentication.sh
  ApplicationStart:
    - location: .aws/stopApplication.sh
    - location: .aws/startApplication.sh 
