version: 0.2
run-as: root
artifacts:
  files:
    - '.aws/*'
    - 'appspec.yml'
    - 'site/**/*'
phases:
    install:
        runtime-versions:
            dotnet: 3.1
        commands:
        - ls -hal
    build:
        commands:
        - find . -type f -name "appsettings.json" -print0 | xargs -0 sed -i -e "s|{cs}|$CS|g"
        - dotnet restore
        - dotnet publish -o site
        - cd  ChoixResto/
        - cat appsettings.json
        - cd ..
